### ISSUE TITLE
Different moves display at both ACAS and external site

### ISSUE THREAD

**Issue by inuxcanor** [Psyyke/A.C.A.S#12]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when at times, in the ACAS website moves were displayed and at the external site different moves were displayed D:

minor inconveniences for me
1. it cant detect that my king has already moved before and its forcing me to castle (idrk if its the website stuff or the chess engine)
2. i forgor...

**Describe the solution you'd like**
welp just make it display always or smth 

**Describe alternatives you've considered**
not rlly thats pretty much it

**Additional context**

![image](https://github.com/Psyyke/A.C.A.S/assets/151096011/9e6e2ea8-77fd-4751-ae53-23b48315bfdd)

**Comment by Hakorr** [comment]
This is a known bug, and it's the first thing I'll fix when I have time to work on the project.

**Comment by inuxcanor** [comment]
ahh i see... thats alright hakorr :D

**Comment by Hakorr** [comment]
Do you know how to replicate that repeatedly?

**Comment by inuxcanor** [comment]
i dont really know how to replicate it because it happens time to time, imma play some games and send it here

**Comment by kusayuzayushko** [comment]
set the SF elo to something high. As the game progresses, it starts doing it more frequently and i think it's because it starts drawing arrows (moves on remote site)  even before the analysis (in the chess-assistant window) is finished. So you can actually  play back-forth move and it'll draw the updated version.
