### ISSUE TITLE
Feature request: Danger Warning / Opponent's moves prediction

### ISSUE THREAD

**Issue by igromanru** [Psyyke/A.C.A.S#15]
First of all, thanks for the awesome, open source tool. 
To my request: 

**The problem**
I would like to have a tool that would do nothing but predict opponent's moves.  
I don't want to be distracted with suggestions for best moves. Not only it prevents me from thinking on my own but also leads to a ban pretty fast.
Best case scenario, I would like to be informed about dangers, e.g. if the opponent is two moves away from trapping me in a pin or fork where I would lose material or jeopardise a checkmate. 

**Possible solution**
I don't know if and how it would be possible to show only the opponent's moves that lead to dangerous situations, so the easiest thing I can think of is to do the same thing you do now for the main player and just show the best X moves for the opponent.  

**Very cheap alternative**
Allow us to show only "Opponent Move Guess" without showing best moves for the player.

**Comment by Hakorr** [comment]
v2.2.2 now allows you to add multiple engines at once, you can make an engine play against you.
