### ISSUE TITLE
Lichess, Issue with finding first move [ISSUE MAKING FIRST MOVE]

### ISSUE THREAD

**Issue by beansofhell** [Psyyke/A.C.A.S#19]
Why ? 
@Hakorr 

https://github.com/Psyyke/A.C.A.S/assets/126506518/a515aac6-3315-4923-ad7e-df61968ad2cc

why is that

**Comment by Hakorr** [comment]
I think it's a harmless bug since it happens at the very start, I'm unsure if it still happens, but if it does, it's not that hard to fix, but not a priority right now.
