### ISSUE TITLE
can't detect colors on chess.com.

### ISSUE THREAD

**Issue by acteam-ux** [Psyyke/A.C.A.S#21]
**Describe the bug**
when i try to use it on chess.com, it always assumes im playing white.

**To Reproduce**
go to chess.com with a browser that has this tool, go to chess.com, start a game, even if you're plaing as black it should show moves for white.

**Expected behavior**
it should show me the moves for black when im playing as black

**Desktop (please complete the following information):**
 - OS: I tried on Windows 11 and Ubuntu 24.04
 - Browser: Chrome
 - Version: 125.0.6422.142

**Additional context**
this tool has always been buggy with chess.com for me, sometimes it doesn't even detect a game IS being played.

**Comment by Hakorr** [comment]
I cannot replicate this.

**Comment by northkoreanangel** [comment]
cannot replicate
