### ISSUE TITLE
[chess.com] 'Natural' Piece Animations Setting breaks calculation

### ISSUE THREAD

**Issue by northkoreanangel** [Psyyke/A.C.A.S#22]
The site fails to calculate the best move when using the "Natural" Piece Animations (accessible within Board and Pieces) setting within chess.com 

**To Reproduce**
1. Go to 'chess.com'
2. Click on 'Settings' on the sidebar, then 'All Settings'
3. Click on 'Board and Pieces' on the sidebar, then see the 'Piece Animations' drop-down menu
4. Change to 'Natural', then click 'Save'
5. A.C.A.S will crash and no longer show pieces or recognize the site being open.

**Desktop:**
 - OS: Windows 10 22H2 (19045.4412)
 - Browser: Firefox (**LibreWolf**), Tampermonkey
 - Version: A.C.A.S **2.1.9**

The site will begin calculation correctly if using 'None', 'Slow', 'Medium', or 'Fast' **('Arcade' not tested)**.

**Comment by Hakorr** [comment]
This is a known bug, which happens due to Chess.com using a canvas to display the board, which is basically just an image. The userscript cannot parse the board layout from an image right now.
