### ISSUE TITLE
Chess (Fischer Random) (играпопереписке not supported)

### ISSUE THREAD

**Issue by Vovadid** [Psyyke/A.C.A.S#23]
**Describe the bug**
I use this script on my phone, open 2 windows, with the board and with your mod, and separate them across the screen. Everywhere the mod works but on Lichess in any mode it opens with an empty board and nothing happens, no hints appear.

**To Reproduce**
1. Download Firefox install the script on your phone 
2. Go to the site Lichess and add it to your home screen 
3. Go to the script and also add to your home screen
4. Launch 2 application windows split on screen 
5. You can see that the script sees that the chess window is open, but the board itself is empty 

**Screenshots**
![Screenshot_2024-06-16-14-15-46-67_3aea4af51f236e4932235fdada7d1643](https://github.com/Psyyke/A.C.A.S/assets/39053957/60ae493d-1fd5-4e33-8a30-cedb42805f53)

Smartphone Information:
 - OS: Android 14; Realme Ui 5.0
 - Phone model: Realme GT3 
 - Browser:  Firefox
 - Version 127.

**Additional context**
I repeat on other sites it works!

**Comment by Hakorr** [comment]
Try changing your language to English.
