### ISSUE TITLE
New platform support : EdChess

### ISSUE THREAD

**Issue by AniketYT** [Psyyke/A.C.A.S#28]
**Is your feature request related to a problem? Please describe.**
I want a new website to be added where I have started to play chess and I think it is getting popular slowly.

**Describe the solution you'd like**
The game website url is: [app.edchess.io](https://app.edchess.io/)

**Additional context**
Do check for copyright stuff before doing it, I don't want you to get into any big trouble.

**Screenshots of the website**
![image](https://github.com/user-attachments/assets/ba752038-89c3-4eff-9948-85b5a8d03100)

![image](https://github.com/user-attachments/assets/bf775d20-3d8b-483a-bcde-549bc26c0fa5)

**Comment by Hakorr** [comment]
Hey, added this in v2.2.1.
