### ISSUE TITLE
Lichess.org Slow Connection, Stop Working During Game Play and Cheat Detection

### ISSUE THREAD

**Issue by prototype1987** [Psyyke/A.C.A.S#32]
**Describe the bug**
The lichess.org site detects the chessboard late, sometimes stops working during the game and my lichess account was closed because I was using a browser plugin. The cheating power was set to 1400 ELO so that it wouldn't be obvious that I was cheating. Also my playing accuracy is below 80%. So neither the cheat detection systems nor the lichess.ort AI should be able to detect cheating. Lichess somehow recognizes the existence of the plugin, not only giving me a hard time in the middle of the game, but also marking the account as a cheat. Even when I disabled the lines drawn on the chessboard, the result was the same.

**To Reproduce**
Just play games on lichess.org for 4-5 days.

**Expected behavior**
Resolving connection delays for Lichess.org. Fixing the game not giving any errors during the game, but just stopping working. Solving the issue where using low ELO and game accuracy below 80% is still detected as cheating. Thanks.

**Desktop**
 - OS: Windows 10 22H2 19045.5073
 - Browser: Brave v1.71.123 Chromium to 130.0.6723.116
 - Extension: Violentmonkey 2.28.0

**Comment by Hakorr** [comment]
> Solving the issue where using low ELO and game accuracy below 80% is still detected as cheating.

That is a major task I don't have the skill nor time for. Someone else can develop an engine which plays like a human and I can add it to A.C.A.S. Anyhow, a bit about the ELO setting on A.C.A.S.

The ELO is a very rough estimate of the power. Stockfish is so powerful and so machine-like that almost any ELO is suspicious. At very low ELOs it still plays like a bot however just makes artificial mistakes to balance the situation. Those artificial mistakes can be detected. The ELO setting tries its best to configure Stockfish to that ELO, however it can't change its bot-like playing style.

> The lichess.org site detects the chessboard late, sometimes stops working during the game

How late? When it stops working, did the board disappear from the A.C.A.S UI as well?

Thanks for the feedback.
