### ISSUE TITLE
Pawn Bug

### ISSUE THREAD

**Issue by Teals53** [Psyyke/A.C.A.S#34]
arrows not showing without refreshing the page when the pawn reaches the end of the board

**Comment by Teals53** [comment]
also takebacks on lichess causing same thing

**Comment by Hakorr** [comment]
Both issues should be solved.

**Comment by Teals53** [comment]
> Both issues should be solved.

where it is fixed ? i mean the script version still same

**Comment by Hakorr** [comment]
> where it is fixed ? i mean the script version still same

Updated it now.
