### ISSUE TITLE
its not detecting the moves

### ISSUE THREAD

**Issue by thechocolatehater** [Psyyke/A.C.A.S#39]
when i open chess.com and play it tells that there is a interruption in connection . or its simply dosent show up or catch the instance

**Comment by Hakorr** [comment]
Disable arcade board animations on Chess.com settings. If it loses connection, play with two separate browser windows next to each other so that you see both A.C.A.S and the chess site at the same time, this way your browser won't stop A.C.A.S from running in the background.
