### ISSUE TITLE
Feature : Auto move

### ISSUE THREAD

**Issue by owlw** [Psyyke/A.C.A.S#6]
**Is your feature request related to a problem? Please describe.**
Nah

**Describe the solution you'd like**
Add auto move

**Describe alternatives you've considered**
Not having it

**Additional context**
i love this

**Comment by Hakorr** [comment]
Not planned right now, why would you want it?

**Comment by owlw** [comment]
so i dont have to play to beat hikaru

**Comment by beansofhell** [comment]
Atleast for Chess.com... the cheating on Chess.com is out of control. Many players I thikn Chess.com fakes account. And make you play against, acient inactive accounts, but against stockfish in their name...


I dont thikn Chess.com has that many players, its seems fake to me idk
