### ISSUE TITLE
Color arrows accodring to move value

### ISSUE THREAD

**Issue by dnld23** [Psyyke/A.C.A.S#7]
It would be nice to color arrows according to stockfish move value. Sometimes 2nd best move is already blunder, would be nice if in case, that alternative move is significantly worse than best move, the arrow color would be red. Or the color would change according to move value.

Also nice feature would be just to be able to display current stockfish value somehow in the real board, so player can know how well he stands without using the move assistance.

**Comment by kusayuzayushko** [comment]
> > display current stockfish value somehow in the real board
> 
> What do you mean by this?

Add an evaluation bar as an option?

**Comment by Hakorr** [comment]
> > > display current stockfish value somehow in the real board
> > 
> > 
> > What do you mean by this?
> 
> Add an evaluation bar as an option?

Doesn't A.C.A.S already have this, just without a specific number shown?

**Comment by suirayhven** [comment]
Adding to this, I think OP is talking about how Chessvision AI handles it where secondary, tertiary, quaternary etc. moves decrease in size according to how good or bad a move is. A secondary move that is close in value to the primary move would have near 100% size while a secondary move that will lose you the game would be smaller.
It would definitely be a good QoL change.

i.e.:

![image](https://github.com/Psyyke/A.C.A.S/assets/160576549/2afbc9cb-5a09-48cf-b5b7-c73eef775841)

here, ChessVision shows its primary move in blue and the next best moves in grey. Bishop xe3 is nearly as good as the primary move so it's close in size while B-e3 loses you more than a point and is thus smaller.

In comparison, A.C.A.S displays the secondary and tertiary move as equal in it's visual hierarchy:

![image](https://github.com/Psyyke/A.C.A.S/assets/160576549/4b957492-9cd8-40c2-823a-f6bfbc4543ab)

**Comment by Hakorr** [comment]
Good point! I'll implement this!
